name: qcharge_flutter
description: Flutter qCharge project

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0
versionCode: 1
versionName: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter_sdk: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  equatable: ^2.0.3
  http: ^0.13.3
  dartz: ^0.10.0
  get_it: ^6.1.1
  flutter_bloc: ^7.2.0
  flutter_svg: ^0.22.0
  cached_network_image: ^3.1.0
  path_provider: ^2.0.2
  flutter_animator: ^3.1.2
  lottie: ^1.1.0
  google_fonts: ^2.1.0
  carousel_slider: ^4.0.0

  flutter_localizations:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^1.2.1


flutter:
  uses-material-design: true

  assets:
    - assets/animations/gifs/
    - assets/animations/lottiefiles/
    - assets/icons/
    - assets/icons/pngs/
    - assets/icons/svgs/
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto.ttf

    - family: CenturyGothic
      fonts:
        - asset: assets/fonts/century_gothic.TTF
